### ISSUE TITLE
preprocessing_data (IndexError: list index out of range)

### ISSUE THREAD

**Issue by rlaengud123** [doronharitan/human_activity_recognition_LRCN#1]
Yours : 

python preprocessing_data.py –-sampled_data_dir dir_where_extracted_videos_would_be_saved\
                             -–row_data_dir add_dir\
                             -–ucf_list_dir add_dir

mine : 
python preprocessing_data.py --row_data_dir=/mnt/home/cmc/lrcn/UCF-101\  --ucf_list_dir=/mnt/home/cmc/lrcn/Data_UCF101/UCF101_video_list --dataset=UCF101

1. i cant find parse( –-sampled_data_dir)
2. i got the error : 
  0%|                                                                                                                                | 0/9537 [00:00<?, ?it/s]Error in reading frames from row video
Error in reading frames from row video
Error in reading frames from row video
Error in reading frames from row video
Error in reading frames from row video
  0%|                                                                                                                                | 0/9537 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "preprocessing_data.py", line 75, in <module>
    main_procesing_data(args, folder_dir)
  File "preprocessing_data.py", line 60, in main_procesing_data
    folder_dir, args.ucf101_fps, processing_mode)
  File "/mnt/home/cmc/lrcn/preprocessing_data/utils_action_recognition.py", line 579, in capture_and_sample_video
    create_new_video(save_path, video_name, image_array)
  File "/mnt/home/cmc/lrcn/preprocessing_data/utils_action_recognition.py", line 455, in create_new_video
    (h, w) = image_array[0].shape[:2]
IndexError: list index out of range

help me

**Comment by rlaengud123** [comment]
solved by
`python preprocessing_data.py --row_data_dir=/mnt/home/cmc/lrcn/UCF-101/ --ucf_list_dir=/mnt/home/cmc/lrcn/Data_UCF101/UCF101_video_list/ --dataset=UCF101`
